### ISSUE TITLE
Retrieve multiple service instances from container

### ISSUE THREAD

**Issue by maxime-jeanson** [gracicot/kangaru#71] opened 2018-09-25 13:54 UTC
allow the container to have multiple instance of a service (multiple impl of an abstract service for instance) and returning either the list of services.  Possible implementation using a `std::unordered_map<std::type_id_t, std::stack<kgr::detail::service_storage>>` or any other ordered collections when it is not a singleton service.

[Discussion of September 25, 2018 7:29 AM](https://gitter.im/gracicot/kangaru?at=5baa1c08fea61370941301ed)

**Comment by gracicot** [comment] 2018-11-15 03:46
On GCC and libstdc++, it's possible to implement this as a multimap, eg `std::unordered_multimap<std::type_id_t, kgr::detail::service_storage>`. This is because `multimap.find()` returns the last inserted element. This is not true for any other platform. Unless there is a way to retrieve the last inserted element for a key in an unordered multimap, the overhead of the stack must be added.

I would really like to not add such overhead solving this issue (another memory indirection, hash maps already are node containers), especially if it can be avoided. If that means depending on another container library (that is not boost) it's fine for me.

**Comment by gracicot** [comment] 2019-03-11 13:19
Duplicate of #81

**Closed by gracicot** 2019-03-11 13:19 UTC
Labels: duplicate, feature
