### ISSUE TITLE
"Error C2039: 'back_inserter': is not a member of 'std'" on MSVC + /permissive-

### ISSUE THREAD

**Issue by QuellaZhang** [gracicot/kangaru#94] opened 2020-02-27 08:38 UTC
Hi All,

The next release MSVC detected "error C2039: 'back_inserter': is not a member of 'std'" when building Kangaru under /permissive- mode. Can you help look at this?

**repro steps:**

1. git clone https://github.com/gracicot/kangaru Kangaru && cd Kangaru
2. set _CL_=/permissive-
3. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DKANGARU_BUILD_EXAMPLES=ON -DKANGARU_TEST=ON -DKANGARU_TEST_CXX14=ON -DKANGARU_TEST_CXX17=ON ..
4. msbuild /m /p:Platform=Win32 /p:Configuration=Release Kangaru.sln /t:Rebuild

**Error info:**
F:\gitP\gracicot\kangaru\include\kangaru\detail\override_storage_service.hpp(25): error C2039: 'back_inserter': is not a member of 'std'
F:\gitP\gracicot\kangaru\include\kangaru\detail\override_storage_service.hpp(25): error C2039: 'back_inserter': is not a member of 'std'

**Comment by gracicot** [comment] 2020-02-27 12:52
Thanks for reporting. I did not catch that error because Visual Studio 2019 was not added into our CI.

There should be a `#include <iterator>` in that header, but it's missing.

I'll fix this bug soon and release a new debug version.

**Comment by gracicot** [comment] 2020-02-27 17:09
The issue is fixed on master, I'll release a bugfix version soon.

**Closed** 2020-02-27 17:08 UTC
